services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      # Workspace itself.
      - ..:/workspaces/copier-template-python-script:cached
