services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - github-token
        - homebrew-github-api-token

    command: sleep infinity

    volumes:
      # Workspace itself.
      - ..:/workspaces/copier-template-python-script:cached

secrets:
  github-token:
    environment: GITHUB_TOKEN
  homebrew-github-api-token:
    environment: HOMEBREW_GITHUB_API_TOKEN
